### ISSUE TITLE
XCode error when opening xcodeproj - missing pbxproj file 

### ISSUE THREAD

**Issue by JohnGoodstadt** [SashenSinghDev/ModularisationExample#1]
When opening each of the 3 xcodeproj files (starter, horizontal, vertical) XCode gives an error message:

"Cannot be opened because it is missing its project.pbxproj file."

Thanks
John Goodstadt

**Comment by SashenSinghDev** [comment]
Hey @JohnGoodstadt thanks for spotting this out, apologies for that. Will update it a little later today 🙏 and let you know when its done

**Comment by SashenSinghDev** [comment]
@JohnGoodstadt the issue has now been resolved, you can get the latest changes 😄 let me know if you experience any other issues

**Comment by JohnGoodstadt** [comment]
Hi

Your Welcome.

I will be using it for the next couple of days, to see if it applies to several current projects I have,  and will let you know of any issues.


Thanks
John goodstadt

***@***.***

**Comment by SashenSinghDev** [comment]
@JohnGoodstadt great thanks :) shout if you have any questions
